/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_handsomezhou_Calculate_Calculate */

#ifndef _Included_com_handsomezhou_Calculate_Calculate
#define _Included_com_handsomezhou_Calculate_Calculate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_handsomezhou_Calculate_Calculate
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_handsomezhou_Calculate_Calculate_plus
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_handsomezhou_Calculate_Calculate
 * Method:    minus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_handsomezhou_Calculate_Calculate_minus
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
